#/bin/bash
rpl "\aAgg" "\mathsf{A}" veqn.tex
rpl "\aboveMin" "\blacktriangle" veqn.tex
rpl "\adjPar" "\omega" veqn.tex
rpl "\adj" "\mathrm{j}" veqn.tex
rpl "\aE" "\aRat^{e}" veqn.tex
rpl "\aFunc" "\mathrm{a}" veqn.tex
rpl "\Age" "Z" veqn.tex
rpl "\age" "z" veqn.tex
rpl "\ALevBF" "\mathbf{A}" veqn.tex
rpl "\aLevBF" "\mathbf{a}" veqn.tex
rpl "\ALev" "A" veqn.tex
rpl "\aLev" "a" veqn.tex
rpl "\Alive" "\cancel{\mathfrak{D}}" veqn.tex
rpl "\Alt" "\grave" veqn.tex
rpl "\aMin" "\underline{\aRat}" veqn.tex
rpl "\ARat" "A" veqn.tex
rpl "\aRat" "a" veqn.tex
rpl "\ASS" "\ensuremath{A}" veqn.tex
rpl "\aSS" "\ensuremath{a}" veqn.tex
rpl "\ATarg" "\check{A}" veqn.tex
rpl "\aTarg" "\check{a}" veqn.tex
rpl "\BE" "\BRat^{e}" veqn.tex
rpl "\bE" "\bRat^{e}" veqn.tex
rpl "\BLevBF" "\mathbf{B}" veqn.tex
rpl "\bLevBF" "\mathbf{b}" veqn.tex
rpl "\BLevE" "\BLev^{e}" veqn.tex
rpl "\bLevE" "\bLev^{e}" veqn.tex
rpl "\BLevU" "\BLev^{u}" veqn.tex
rpl "\bLevU" "\bLev^{u}" veqn.tex
rpl "\BLev" "B" veqn.tex
rpl "\bLev" "b" veqn.tex
rpl "\bMin" "\underline{\bRat}" veqn.tex
rpl "\bRatE" "b}^{e" veqn.tex
rpl "\BRatE" "B}^{e" veqn.tex
rpl "\bRatU" "b}^{u" veqn.tex
rpl "\BRat" "B" veqn.tex
rpl "\bRat" "b" veqn.tex
rpl "\bTargE" "\check{b}^{e}" veqn.tex
rpl "\BTargTarg" "\Target{\Target{\BRat}}" veqn.tex
rpl "\bTargTarg" "\Target{\Target{\bRat}}" veqn.tex
rpl "\BTarg" "\check{B}" veqn.tex
rpl "\bTarg" "\check{b}" veqn.tex
rpl "\BU" "{B}^{u}" veqn.tex
rpl "\bU" "{b}^{u}" veqn.tex
rpl "\cAgg" "\pmb{C}" veqn.tex
rpl "\CARA" "\alpha" veqn.tex
rpl "\ccRat" "\mathsf{c}" veqn.tex
rpl "\CDF" "\mathcal{F}" veqn.tex
rpl "\CEndFunc" "\mathfrak{C}" veqn.tex
rpl "\cEndFunc" "\mathfrak{c}" veqn.tex
rpl "\cEss" "{c}^{e}" veqn.tex
rpl "\CE" "\CRat^{e}" veqn.tex
rpl "\cE" "\cRat^{e}" veqn.tex
rpl "\cFuncAbove" "\bar{\mathrm{c}}" veqn.tex
rpl "\cFuncBelow" "\uline{\mathrm{c}}" veqn.tex
rpl "\cFuncMax" "\bar{\bar{\mathrm{c}}}" veqn.tex
rpl "\CFunc" "\mathrm{C}" veqn.tex
rpl "\cFunc" "\mathrm{c}" veqn.tex
rpl "\cFunc" "\mathrm{c}" veqn.tex
rpl "\CGroOverG" "\Upsilon" veqn.tex
rpl "\CGroOverR" "\Phi" veqn.tex
rpl "\CGroPF" "\Lambda" veqn.tex
rpl "\cGroPF" "\lambda" veqn.tex
rpl "\CGroPS" "\chi" veqn.tex
rpl "\chiFunc" "\pmb{\chi}" veqn.tex
rpl "\Chi" "\mathrm{X}" veqn.tex
rpl "\CLevBF" "\mathbf{C}" veqn.tex
rpl "\cLevBF" "\mathbf{c}" veqn.tex
rpl "\CLevE" "\CLev^{e}" veqn.tex
rpl "\cLevE" "\cLev^{e}" veqn.tex
rpl "\cLevFunc" "\pmb{\cFunc}" veqn.tex
rpl "\CLevU" "\CLev^{u}" veqn.tex
rpl "\cLevU" "\cLev^{u}" veqn.tex
rpl "\cLev" "c" veqn.tex
rpl "\CLev" "C" veqn.tex
rpl "\Cons" "C" veqn.tex
rpl "\cons" "c" veqn.tex
rpl "\corr" "\varrho" veqn.tex
rpl "\cPDVFunc" "\mathbb{C}" veqn.tex
rpl "\CPDV" "\text{PDV($C$)}" veqn.tex
rpl "\cPPP" "\cons^{\prime\prime\prime}" veqn.tex
rpl "\cPP" "\cons^{\prime\prime}" veqn.tex
rpl "\cP" "\cons^{\prime}" veqn.tex
rpl "\cRatBF" "\pmb{c}" veqn.tex
rpl "\CRatE" "\CRat^{e}" veqn.tex
rpl "\cRatE" "\cRat^{e}" veqn.tex
rpl "\CRatU" "\CRat^{u}" veqn.tex
rpl "\cRatU" "\cRat^{u}" veqn.tex
rpl "\CRat" "C" veqn.tex
rpl "\cRat" "c" veqn.tex
rpl "\CRRA" "\rho" veqn.tex
rpl "\CTargE" "\CTarg^{\null}" veqn.tex
rpl "\cTargE" "\Target{c}^{e}" veqn.tex
rpl "\cTargTarg" "\Target{\Target{\cRat}}" veqn.tex
rpl "\CTarg" "\Target{C}" veqn.tex
rpl "\cTarg" "\Target{c}" veqn.tex
rpl "\curr" "1" veqn.tex
rpl "\Curr" "t" veqn.tex
rpl "\CU" "\CRat^{u}" veqn.tex
rpl "\cU" "\cRat^{u}" veqn.tex
rpl "\dRat" "d" veqn.tex
rpl "\debtLim" "\mathsf{d}" veqn.tex
rpl "\Debt" "D" veqn.tex
rpl "\debt" "d" veqn.tex
rpl "\DeprFac" "\daleth" veqn.tex
rpl "\Depr" "\daleth" veqn.tex
rpl "\depr" "\delta" veqn.tex
rpl "\deprRte" "\delta" veqn.tex
rpl "\DiscAltuAdj" "\underline{\underline{\beth}}" veqn.tex
rpl "\DiscAlt" "\beth" veqn.tex
rpl "\Discount" "\beta" veqn.tex
rpl "\DiscRate" "\vartheta" veqn.tex
rpl "\DiscRte" "\vartheta" veqn.tex
rpl "\DiscFac" "\beta" veqn.tex
rpl "\DivGro" "\mathsf{G}" veqn.tex
rpl "\divGro" "\mathsf{g}" veqn.tex
rpl "\Div" "D" veqn.tex
rpl "\div" "d" veqn.tex
rpl "\DLev" "D" veqn.tex
rpl "\Dvdnd" "\mathbf{D}" veqn.tex
rpl "\dvdnd" "d" veqn.tex
rpl "\edvdnd" "\grave{\dvdnd}" veqn.tex
rpl "\EEndMap" "\mathsf{E}" veqn.tex
rpl "\effUnits" "X" veqn.tex
rpl "\eFunc" "\mathrm{e}" veqn.tex
rpl "\ELev" "E" veqn.tex
rpl "\ek" "\lambda" veqn.tex
rpl "\EmpGro" "\Xi" veqn.tex
rpl "\empGro" "\xi" veqn.tex
rpl "\empState" "\xi" veqn.tex
rpl "\EpremLog" "\varphi" veqn.tex
rpl "\EPrem" "\Phi" veqn.tex
rpl "\eprem" "\phi" veqn.tex
rpl "\EpShkInv" "\Ex[\pShk^{-1}]" veqn.tex
rpl "\erate" "\cancel{\mho}" veqn.tex
rpl "\error" "\epsilon" veqn.tex
rpl "\Err" "Z" veqn.tex
rpl "\err" "z" veqn.tex
rpl "\err" "z" veqn.tex
rpl "\Estdr" "\sigma_{\risky}" veqn.tex
rpl "\Evarr" "\sigma_{\risky}^{2}" veqn.tex
rpl "\EVarr" "\sigma_{\Risky}^{2}" veqn.tex
rpl "\expend" "\xi" veqn.tex
rpl "\Ex" "\mathbb{E}" veqn.tex
rpl "\FDist" "\mathcal{F}" veqn.tex
rpl "\fDist" "\mathcal{f}" veqn.tex
rpl "\FFunc" "\mathrm{F}" veqn.tex
rpl "\fFunc" "\mathrm{f}" veqn.tex
rpl "\FLev" "F" veqn.tex
rpl "\fLev" "f" veqn.tex
rpl "\fPP" "\mathrm{f}^{\prime\prime}" veqn.tex
rpl "\FPP" "\mathrm{F}^{\prime\prime}" veqn.tex
rpl "\fP" "\mathrm{f}^{\prime}" veqn.tex
rpl "\FP" "\mathrm{F}^{\prime}" veqn.tex
rpl "\GLev" "G" veqn.tex
rpl "\GovNW" "N" veqn.tex
rpl "\govNW" "n" veqn.tex
rpl "\GovSpend" "X" veqn.tex
rpl "\govSpend" "x" veqn.tex
rpl "\Habit" "H" veqn.tex
rpl "\Habit" "H" veqn.tex
rpl "\habit" "h" veqn.tex
rpl "\Ham" "\mathcal{H}" veqn.tex
rpl "\HARKcore" "\texttt{HARKcore}" veqn.tex
rpl "\hEndMin" "\underline{\mathfrak{h}}" veqn.tex
rpl "\hEnd" "\mathfrak{h}" veqn.tex
rpl "\hFunc" "\mathrm{h}" veqn.tex
rpl "\Hi" "\hat" veqn.tex
rpl "\HLev" "H" veqn.tex
rpl "\HLevBF" "\mathbf{H}" veqn.tex
rpl "\hLevBF" "\mathbf{h}" veqn.tex
rpl "\HLev" "\pmb{H}" veqn.tex
rpl "\hLev" "\pmb{h}" veqn.tex
rpl "\hMin" "\underline{\h}" veqn.tex
rpl "\HMin" "\underline{H}" veqn.tex
rpl "\hours" "\mathfrak{h}" veqn.tex
rpl "\Hours" "\mathfrak{H}" veqn.tex
rpl "\HRat" "H" veqn.tex
rpl "\hRat" "h" veqn.tex
rpl "\h" "h" veqn.tex
rpl "\H" "H" veqn.tex
rpl "\iFunc" "\mathrm{i}" veqn.tex
rpl "\IFunc" "\mathrm{I}" veqn.tex
rpl "\ILev" "I" veqn.tex
rpl "\iLev" "i" veqn.tex
rpl "\impg" "{\imath}_{\pGro}" veqn.tex
rpl "\ImpG" "{\Im}_{\PGro}" veqn.tex
rpl "\impr" "{\imath}_{\rfree}" veqn.tex
rpl "\ImpR" "{\Im}_{\Rfree}" veqn.tex
rpl "\Inc" "{Y}" veqn.tex
rpl "\inc" "{y}" veqn.tex
rpl "\InvEpShkInv" "\acute{\psi}" veqn.tex
rpl "\InvEpShkInv" "\underline{\psi}" veqn.tex
rpl "\Inv" "{I}" veqn.tex
rpl "\inv" "{i}" veqn.tex
rpl "\IRat" "I" veqn.tex
rpl "\iRat" "i" veqn.tex
rpl "\itc" "\zeta" veqn.tex
rpl "\jFunc" "\mathrm{j}" veqn.tex
rpl "\JLev" "J" veqn.tex
rpl "\kapRent" "\varkappa" veqn.tex
rpl "\kapShare" "\alpha" veqn.tex
rpl "\Kap" "{K}" veqn.tex
rpl "\kap" "{k}" veqn.tex
rpl "\KFunc" "\mathrm{K}" veqn.tex
rpl "\kFunc" "\mathrm{k}" veqn.tex
rpl "\KLevBF" "\mathbf{K}" veqn.tex
rpl "\kLevBF" "\mathbf{k}" veqn.tex
rpl "\KLev" "K" veqn.tex
rpl "\kLev" "k" veqn.tex
rpl "\kPriceAfterITC" "\mathscr{P}" veqn.tex
rpl "\kPrice" "\mathsf{P}" veqn.tex
rpl "\KRat" "K" veqn.tex
rpl "\kRat" "k" veqn.tex
rpl "\kTargE" "\Target{k}^{e}" veqn.tex
rpl "\kTarg" "\Target{k}" veqn.tex
rpl "\labor" "\ell" veqn.tex
rpl "\Labor" "L" veqn.tex
rpl "\labShare" "\nu" veqn.tex
rpl "\Leisure" "Z" veqn.tex
rpl "\leisure" "z" veqn.tex
rpl "\leiShare" "\zeta" veqn.tex
rpl "\LGro" "\Lambda" veqn.tex
rpl "\lGro" "\lambda" veqn.tex
rpl "\LLevBF" "\mathbf{L}" veqn.tex
rpl "\lLevBF" "\pmb{\ell}" veqn.tex
rpl "\lLev" "\ell" veqn.tex
rpl "\LLev" "L" veqn.tex
rpl "\Lo" "\check" veqn.tex
rpl "\LRat" "L" veqn.tex
rpl "\MaxMaxMPC" "\bar{\bar{\kappa}}" veqn.tex
rpl "\MaxMinMPC" "\hat{\underline{\kappa}}" veqn.tex
rpl "\MaxMPC" "\bar{\kappa}" veqn.tex
rpl "\MaxMPS" "\PatR" veqn.tex
rpl "\Mean" "\mathbb{M}" veqn.tex
rpl "\mEss" "\check{m}^{e}" veqn.tex
rpl "\ME" "\MRat^{e}" veqn.tex
rpl "\mE" "\mRat^{e}" veqn.tex
rpl "\mFunc" "\mathrm{m}" veqn.tex
rpl "\MinMinMPC" "\underline{\kappa}" veqn.tex
rpl "\MinMPC" "\uline{\kappa}" veqn.tex
rpl "\MinMPS" "\pZero^{1/\CRRA} \PatR" veqn.tex
rpl "\MLevBF" "\mathbf{M}" veqn.tex
rpl "\mLevBF" "\mathbf{m}" veqn.tex
rpl "\mLevBF" "\mathbf{m}" veqn.tex
rpl "\mLevE" "\mLev^{e}" veqn.tex
rpl "\MLev" "M" veqn.tex
rpl "\mLev" "m" veqn.tex
rpl "\MPCE" "\MPC^{e}" veqn.tex
rpl "\MPCFunc" "\pmb{\kappa}" veqn.tex
rpl "\MPCPPF" "\Pi" veqn.tex
rpl "\MPCP" "\pi" veqn.tex
rpl "\MPCU" "\MPC^{u}" veqn.tex
rpl "\MPC" "\kappa" veqn.tex
rpl "\MPSFunc" "\pmb{lambda}" veqn.tex
rpl "\MPS" "\lambda" veqn.tex
rpl "\MRatE" "\MRat^{e}" veqn.tex
rpl "\mRatE" "\mRat^{e}" veqn.tex
rpl "\MRat" "M" veqn.tex
rpl "\mRat" "m" veqn.tex
rpl "\MSS" "\breve{M}" veqn.tex
rpl "\mSS" "\breve{m}" veqn.tex
rpl "\mTarg" "\check{m}" veqn.tex
rpl "\MU" "{M}^{u}" veqn.tex
rpl "\mU" "{m}^{u}" veqn.tex
rpl "\next" "2" veqn.tex
rpl "\Next" "t+1" veqn.tex
rpl "\nFunc" "\mathrm{n}" veqn.tex
rpl "\NLev" "N" veqn.tex
rpl "\nLev" "n" veqn.tex
rpl "\NRat" "N" veqn.tex
rpl "\nRat" "n" veqn.tex
rpl "\Num" "N" veqn.tex
rpl "\OLevBF" "O" veqn.tex
rpl "\oLevBF" "\mathbf{o}" veqn.tex
rpl "\OLev" "O" veqn.tex
rpl "\oLev" "\pmb{o}" veqn.tex
rpl "\ORat" "O" veqn.tex
rpl "\oRat" "o" veqn.tex
rpl "\Pareto" "\zeta" veqn.tex
rpl "\PatPGroAdj" "\text{\pmb{\Thorn}}_{\acute{\PGro}}" veqn.tex
rpl "\patpGroAdj" "\text{\thorn}_{\acute{\pGro}}" veqn.tex
rpl "\patpGrohat" "\hat{\text{\thorn}}_{\pGro}" veqn.tex
rpl "\PatPGro" "\text{\pmb{\Thorn}}_{\PGro}" veqn.tex
rpl "\patpGro" "\text{\thorn}_{\pGro}" veqn.tex
rpl "\PatR" "\text{\pmb{\Thorn}}_{\Rfree}" veqn.tex
rpl "\patr" "\text{\thorn}_{\rfree}" veqn.tex
rpl "\PatU" "\text{\pmb{\Thorn}}_{\urate}" veqn.tex
rpl "\patu" "\text{\thorn}_{\urate}" veqn.tex
rpl "\PatWGro" "\text{\pmb{\Thorn}}_{\WGro}" veqn.tex
rpl "\patwGro" "\text{\thorn}_{\wGro}" veqn.tex
rpl "\Pat" "\text{\pmb{\Thorn}}" veqn.tex
rpl "\pat" "\text{\thorn}" veqn.tex
rpl "\pDeadRate" "\grave{\cancel{\mathsf{d}}}" veqn.tex
rpl "\pDead" "\mathfrak{D}" veqn.tex
rpl "\pDieRate" "\grave{\mathsf{d}}" veqn.tex
rpl "\pDies" "\mathrm{d}" veqn.tex
rpl "\PDies" "\mathsf{D}" veqn.tex
rpl "\PDV" "\mathbb{P}" veqn.tex
rpl "\PGroAdj" "\underline{\PGro}" veqn.tex
rpl "\pGroAdj" "\underline{\pGro}" veqn.tex
rpl "\PGrouAdj" "\underline{\underline{\PGro}}" veqn.tex
rpl "\pGrouAdj" "\underline{\underline{{\pGro}}}" veqn.tex
rpl "\PGro" "\Gamma" veqn.tex
rpl "\pGro" "\gamma" veqn.tex
rpl "\phiFunc" "\digamma" veqn.tex
rpl "\PIHMPC" "\varkappa" veqn.tex
rpl "\PInc" "P" veqn.tex
rpl "\PLabor" "P" veqn.tex
rpl "\Plabor" "P" veqn.tex
rpl "\PLevBF" "\mathbf{P}" veqn.tex
rpl "\pLevBF" "\mathbf{p}" veqn.tex
rpl "\PLev" "P" veqn.tex
rpl "\pLev" "\pmb{p}" veqn.tex
rpl "\PLev" "P" veqn.tex
rpl "\PLives" "\cancel{\PDies}" veqn.tex
rpl "\pLives" "\cancel{\pDies}" veqn.tex
rpl "\pNotZero" "\cancel{\wp}" veqn.tex
rpl "\PopE" "\mathcal{E}" veqn.tex
rpl "\popE" "e" veqn.tex
rpl "\PopGro" "\Xi" veqn.tex
rpl "\popGro" "\xi" veqn.tex
rpl "\PopLev" "\pmb{N}" veqn.tex
rpl "\PopU" "\mathcal{U}" veqn.tex
rpl "\Pop" "L" veqn.tex
rpl "\PostITC" "\cancel{\zeta}" veqn.tex
rpl "\power" "\eta" veqn.tex
rpl "\pPDVFunc" "\mathbb{P}" veqn.tex
rpl "\PPDV" "\text{PDV($P$)}" veqn.tex
rpl "\pRat" "p" veqn.tex
rpl "\Price" "\mathsf{P}" veqn.tex
rpl "\ProdFunc" "\mathrm{F}" veqn.tex
rpl "\ProdFunc" "\mathrm{F}" veqn.tex
rpl "\prodFunc" "\mathrm{f}" veqn.tex
rpl "\prudEx" "\omega" veqn.tex
rpl "\prud" "\eta" veqn.tex
rpl "\pSav" "\phi" veqn.tex
rpl "\pShkMin" "\underline{\psi}" veqn.tex
rpl "\PShk" "\Psi" veqn.tex
rpl "\PermShkAgg" "\Psi" veqn.tex
rpl "\PermShk" "\Psi" veqn.tex
rpl "\permShk" "\psi" veqn.tex
rpl "\pShk" "\psi" veqn.tex
rpl "\permShkInd" "\psi" veqn.tex
rpl "\pshk" "\psi" veqn.tex
rpl "\PtyGro" "\Phi" veqn.tex
rpl "\ptyGro" "\phi" veqn.tex
rpl "\PtyLab" "\mathrm{Z}" veqn.tex
rpl "\ptyLab" "z" veqn.tex
rpl "\PtyLev" "A" veqn.tex
rpl "\ptyLev" "a" veqn.tex
rpl "\pZero" "\wp" veqn.tex
rpl "\QLev" "Q" veqn.tex
rpl "\q" "\koppa" veqn.tex
rpl "\RCpnd" "\mathbf{R}" veqn.tex
rpl "\RevFunc" "\pmb{\Pi}" veqn.tex
rpl "\revFunc" "\pmb{\pi}" veqn.tex
rpl "\Rev" "\Pi" veqn.tex
rpl "\rev" "\pi" veqn.tex
rpl "\rfree" "\mathsf{r}" veqn.tex
rpl "\Rfree" "\mathsf{R}" veqn.tex
rpl "\RFunc" "\mathrm{R}" veqn.tex
rpl "\RGross" "\breve{\mathsf{R}}" veqn.tex
rpl "\rGross" "\breve{\mathsf{r}}" veqn.tex
rpl "\RiskyAlt" "\acute{\mathbf{R}}" veqn.tex
rpl "\riskyAlt" "\acute{\mathbf{r}}" veqn.tex
rpl "\riskyshare" "\varsigma" veqn.tex
rpl "\Risky" "\mathbf{R}" veqn.tex
rpl "\risky" "\mathbf{r}" veqn.tex
rpl "\RLev" "R" veqn.tex
rpl "\RnormWGro" "\mathcal{R}_{\WGro}" veqn.tex
rpl "\rnormwGro" "\mathit{r}_{\wGro}" veqn.tex
rpl "\Rnorm" "\mathcal{R}" veqn.tex
rpl "\rnorm" "\mathit{r}" veqn.tex
rpl "\Rport" "\pmb{\mathfrak{R}}" veqn.tex
rpl "\rport" "\pmb{\mathfrak{r}}" veqn.tex
rpl "\rProd" "\mathit{r}" veqn.tex
rpl "\Rprod" "\mathscr{R}" veqn.tex
rpl "\rprod" "\mathscr{r}" veqn.tex
rpl "\RProd" "\mathsf{R}" veqn.tex
rpl "\RSave" "\ushort{\Rfree}" veqn.tex
rpl "\rsave" "\ushort{\rfree}" veqn.tex
rpl "\RBoro" "\bar{\Rfree}" veqn.tex
rpl "\rboro" "\bar{\rfree}" veqn.tex
rpl "\R" "\Rfree" veqn.tex
rpl "\saveRate" "\grave{s}" veqn.tex
rpl "\Save" "S" veqn.tex
rpl "\save" "s" veqn.tex
rpl "\SDF" "\MLev" veqn.tex
rpl "\sdr" "\mRat" veqn.tex
rpl "\Seniority" "\mathsf{X}" veqn.tex
rpl "\seniority" "\mathsf{x}" veqn.tex
rpl "\SeverancePayment" "\mathcal{S}" veqn.tex
rpl "\SeveranceRatio" "\varsigma" veqn.tex
rpl "\Severance" "\varsigma" veqn.tex
rpl "\SE" "\SRat^{e}" veqn.tex
rpl "\sE" "\sRat^{e}" veqn.tex
rpl "\sFunc" "\mathrm{s}" veqn.tex
rpl "\shk" "\phi" veqn.tex
rpl "\Shk" "\Phi" veqn.tex
rpl "\ShkLogZeroLogStd" "\sigma_{\cancel{\ShkMeanOneLog}}" veqn.tex
rpl "\ShkLogZeroLogVar" "\sigma_{\cancel{\ShkMeanOneLog}}^{2}" veqn.tex
rpl "\ShkLogZeroLog" "\cancel{\ShkMeanOneLog}" veqn.tex
rpl "\ShkLogZero" "\cancel{\ShkMeanOne}" veqn.tex
rpl "\ShkMeanOneLogStd" "\sigma_{\ShkMeanOneLog}" veqn.tex
rpl "\ShkMeanOneLogVar" "\sigma^{2}_{\ShkMeanOneLog}" veqn.tex
rpl "\ShkMeanOneLog" "\theta" veqn.tex
rpl "\ShkMeanOne" "\Theta" veqn.tex
rpl "\SLevBF" "\mathbf{S}" veqn.tex
rpl "\sLevBF" "\mathbf{s}" veqn.tex
rpl "\SLevE" "\SLev^{e}" veqn.tex
rpl "\sLevE" "\sLev^{e}" veqn.tex
rpl "\SLevU" "\SLev^{u}" veqn.tex
rpl "\sLevU" "\sLev^{u}" veqn.tex
rpl "\SLev" "S" veqn.tex
rpl "\sLev" "s" veqn.tex
rpl "\srate" "\varsigma" veqn.tex
rpl "\SRatE" "\SRat^{e}" veqn.tex
rpl "\sRatE" "\sRat^{e}" veqn.tex
rpl "\SRatU" "\SRat^{u}" veqn.tex
rpl "\sRatU" "\sRat^{u}" veqn.tex
rpl "\SRat" "S" veqn.tex
rpl "\sRat" "s" veqn.tex
rpl "\STargE" "\Target{\SRat}^{\null}" veqn.tex
rpl "\sTargE" "\Target{\sRat}^{\null}" veqn.tex
rpl "\STargTarg" "\Target{\Target{\SRat}}" veqn.tex
rpl "\sTargTarg" "\Target{\Target{\sRat}}" veqn.tex
rpl "\STarg" "\Target{\SRat}" veqn.tex
rpl "\sTarg" "\Target{\sRat}" veqn.tex
rpl "\Steady" "\bar" veqn.tex
rpl "\Stocks" "{S}" veqn.tex
rpl "\stocks" "{s}" veqn.tex
rpl "\straight" "\Pi" veqn.tex
rpl "\Surplus" "Z" veqn.tex
rpl "\surplus" "z" veqn.tex
rpl "\SU" "\SRat^{u}" veqn.tex
rpl "\sU" "\sRat^{u}" veqn.tex
rpl "\Target" "\check" veqn.tex
rpl "\TaxCombInv" "\mathcal{T}^{-1}" veqn.tex
rpl "\TaxComb" "\mathcal{T}" veqn.tex
rpl "\TaxCorp" "\tau" veqn.tex
rpl "\taxDep" "\partial" veqn.tex
rpl "\TaxFree" "\cancel{\Tax}" veqn.tex
rpl "\TaxLev" "T" veqn.tex
rpl "\TaxNetTrans" "Z" veqn.tex
rpl "\taxNetTrans" "z" veqn.tex
rpl "\TaxPaid" "T" veqn.tex
rpl "\TaxRate" "t" veqn.tex
rpl "\TaxUI" "\tau" veqn.tex
rpl "\Tax" "\tau" veqn.tex
rpl "\tax" "\tau" veqn.tex
rpl "\tBak" "\pmb{n}" veqn.tex
rpl "\TEatBak" "\mathtt{q}" veqn.tex
rpl "\TEat" "\TEnd" veqn.tex
rpl "\TEndBak" "\mathsf{p}" veqn.tex
rpl "\TEnd" "T" veqn.tex
rpl "\TermTime" "T" veqn.tex
rpl "\tFwd" "n" veqn.tex
rpl "\tHorOfm" "\pmb{n}" veqn.tex
rpl "\tHor" "\mathsf{n}" veqn.tex
rpl "\timeRate" "\vartheta" veqn.tex
rpl "\tinyAmount" "\epsilon" veqn.tex
rpl "\TLev" "T" veqn.tex
rpl "\TMap" "\mathscr{T}" veqn.tex
rpl "\tNow" "t" veqn.tex
rpl "\tShkAll" "\xi" veqn.tex
rpl "\tShkEmpMin" "\underline{\theta}" veqn.tex
rpl "\TShkEmp" "\Theta" veqn.tex
rpl "\tShkEmp" "\theta" veqn.tex
rpl "\tShkEmp" "\theta" veqn.tex
rpl "\tranShkInd" "\theta" veqn.tex
rpl "\TranShkAgg" "\Theta" veqn.tex
rpl "\TShk" "\Xi" veqn.tex
rpl "\tShk" "\xi" veqn.tex
rpl "\tshk" "\xi" veqn.tex
rpl "\tSS" "t" veqn.tex
rpl "\tThen" "\tau" veqn.tex
rpl "\uFunc" "{\mathrm{u}}" veqn.tex
rpl "\uInvEpShkuInv" "\underline{\underline{\psi}}" veqn.tex
rpl "\ULev" "U" veqn.tex
rpl "\uLev" "u" veqn.tex
rpl "\unins" "\zeta" veqn.tex
rpl "\uPDVFunc" "\mathbb{U}" veqn.tex
rpl "\uPmt" "\mu" veqn.tex
rpl "\uPPP" "{\mathrm{u}^{\prime\prime\prime}}" veqn.tex
rpl "\uPP" "{\mathrm{u}^{\prime\prime}}" veqn.tex
rpl "\uP" "{\mathrm{u}^{\prime}}" veqn.tex
rpl "\urate" "\mho" veqn.tex
rpl "\utilFunc" "\mathrm{u}" veqn.tex
rpl "\util" "u" veqn.tex
rpl "\ValAlt" "\mathcal{V}" veqn.tex
rpl "\valfn" "\mathrm{v}" veqn.tex
rpl "\Value" "\mathrm{V}" veqn.tex
rpl "\VEndFunc" "\mathfrak{V}" veqn.tex
rpl "\vEndFunc" "\mathfrak{v}" veqn.tex
rpl "\VEnd" "\mathfrak{V}" veqn.tex
rpl "\vEnd" "\mathfrak{v}" veqn.tex
rpl "\vEss" "\check{v}^{e}" veqn.tex
rpl "\VE" "{V}^{e}" veqn.tex
rpl "\vE" "{v}^{e}" veqn.tex
rpl "\vFirm" "\mathrm{e}" veqn.tex
rpl "\VFunc" "\mathrm{V}" veqn.tex
rpl "\vFunc" "\mathrm{v}" veqn.tex
rpl "\VInv" "\Lambda" veqn.tex
rpl "\vInv" "\scriptstyle \Lambda \displaystyle" veqn.tex
rpl "\vk" "\lambda" veqn.tex
rpl "\vLevBF" "\mathbf{v}" veqn.tex
rpl "\VLevFunc" "\pmb{\mathrm{V}}" veqn.tex
rpl "\vLevFunc" "\pmb{\mathrm{v}}" veqn.tex
rpl "\VLev" "V" veqn.tex
rpl "\vLev" "v" veqn.tex
rpl "\vNorm" "\mathrm{w}" veqn.tex
rpl "\VNum" "V" veqn.tex
rpl "\vNum" "v" veqn.tex
rpl "\vOptAlt" "\Alt{\tilde{\mathfrak{v}}}" veqn.tex
rpl "\vOpt" "\tilde{\mathfrak{v}}" veqn.tex
rpl "\VRat" "V" veqn.tex
rpl "\vRat" "v" veqn.tex
rpl "\vTarg" "\Target{\vRat}" veqn.tex
rpl "\VU" "{V}^{u}" veqn.tex
rpl "\vU" "{v}^{u}" veqn.tex
rpl "\Wage" "\mathsf{W}" veqn.tex
rpl "\wage" "\mathsf{w}" veqn.tex
rpl "\WAllLev" "\mathbf{O}" veqn.tex
rpl "\wAllLev" "\mathbf{o}" veqn.tex
rpl "\WAllRat" "O" veqn.tex
rpl "\wAllRat" "o" veqn.tex
rpl "\WAll" "{O}" veqn.tex
rpl "\wAll" "{o}" veqn.tex
rpl "\WBeg" "\KLev" veqn.tex
rpl "\wBeg" "\kLev" veqn.tex
rpl "\Wealth" "O" veqn.tex
rpl "\wealth" "o" veqn.tex
rpl "\WEndRat" "\ARat" veqn.tex
rpl "\wEndRat" "\aRat" veqn.tex
rpl "\WEnd" "\ALev" veqn.tex
rpl "\wEnd" "\aLev" veqn.tex
rpl "\Wend" "\ARat" veqn.tex
rpl "\wend" "\aRat" veqn.tex
rpl "\wFunc" "\mathrm{w}" veqn.tex
rpl "\WGroPF" "\mathsf{G}" veqn.tex
rpl "\WGro" "\mathsf{G}" veqn.tex
rpl "\wGro" "\mathsf{g}" veqn.tex
rpl "\whumMin" "\underline{\hRat}" veqn.tex
rpl "\WHum" "\HLev" veqn.tex
rpl "\wHum" "\hLev" veqn.tex
rpl "\Whum" "\HRat" veqn.tex
rpl "\whum" "\hRat" veqn.tex
rpl "\WLev" "W" veqn.tex
rpl "\wLev" "\pmb{w}" veqn.tex
rpl "\WMid" "\BLev" veqn.tex
rpl "\WMid" "\BLev" veqn.tex
rpl "\wMid" "\bLev" veqn.tex
rpl "\Wmid" "\BRat" veqn.tex
rpl "\wmid" "\bRat" veqn.tex
rpl "\WMkt" "\MLev" veqn.tex
rpl "\wMkt" "\mLev" veqn.tex
rpl "\wmkt" "\mLev" veqn.tex
rpl "\wNet" "x" veqn.tex
rpl "\WNet" "X" veqn.tex
rpl "\WPre" "{K}" veqn.tex
rpl "\wPre" "{k}" veqn.tex
rpl "\wRat" "o" veqn.tex
rpl "\WRat" "O" veqn.tex
rpl "\wTot" "\mathbf{o}" veqn.tex
rpl "\WTot" "\mathbf{O}" veqn.tex
rpl "\wtot" "o" veqn.tex
rpl "\Wtot" "O" veqn.tex
rpl "\xFer" "\chi" veqn.tex
rpl "\XFer" "X" veqn.tex
rpl "\xFunc" "\mathrm{x}" veqn.tex
rpl "\XLev" "X" veqn.tex
rpl "\xLev" "x" veqn.tex
rpl "\xpend" "\xi" veqn.tex
rpl "\XperGro" "\mathsf{X}" veqn.tex
rpl "\xperGro" "\mathsf{x}" veqn.tex
rpl "\XRat" "X" veqn.tex
rpl "\xRat" "x" veqn.tex
rpl "\yFunc" "\mathrm{y}" veqn.tex
rpl "\yLevBF" "\mathbf{y}" veqn.tex
rpl "\YLev" "Y" veqn.tex
rpl "\yLev" "y" veqn.tex
rpl "\YRat" "Y" veqn.tex
rpl "\yRat" "y" veqn.tex
rpl "\yTargE" "\check{y}^{e}" veqn.tex
rpl "\yTarg" "\check{y}" veqn.tex
rpl "\zAgg" "\pmb{Z}" veqn.tex
rpl "\zFunc" "\mathrm{z}" veqn.tex
rpl "\ZLevBF" "\mathbf{Z}" veqn.tex
rpl "\zLevBF" "\mathbf{z}" veqn.tex
rpl "\zLevBF" "\pmb{z}" veqn.tex
rpl "\ZLev" "Z" veqn.tex
rpl "\zLev" "z" veqn.tex
rpl "\ZRat" "Z" veqn.tex
rpl "\zRat" "z" veqn.tex
rpl "\NFALev" "\NLev" veqn.tex
rpl "\NFARat" "\NRat" veqn.tex
rpl "\NI" "Z" veqn.tex
rpl "\GDPLev" "\pmb{P}" veqn.tex
rpl "\GDPRat" "P" veqn.tex
rpl "\GDPGro" "\gimel" veqn.tex
rpl "\gdpLev" "\pmb{p}" veqn.tex
rpl "\gdpRat" "p" veqn.tex
rpl "\weight" "\omega" veqn.tex
rpl "\Severance" "\kappa" veqn.tex
