#/bin/bash
rpl "\aAgg" "\mathsf{A}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aboveMin" "\blacktriangle" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\adjPar" "\omega" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\adj" "\mathrm{j}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aE" "\aRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aFunc" "\mathrm{a}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Age" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\age" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ALevBF" "\mathbf{A}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aLevBF" "\mathbf{a}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ALev" "A" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aLev" "a" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Alive" "\cancel{\mathfrak{D}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Alt" "\grave" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aMin" "\underline{\aRat}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ARat" "A" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aRat" "a" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ASS" "\ensuremath{A}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aSS" "\ensuremath{a}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ATarg" "\check{A}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\aTarg" "\check{a}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BE" "\BRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bE" "\bRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BLevBF" "\mathbf{B}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bLevBF" "\mathbf{b}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BLevE" "\BLev^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bLevE" "\bLev^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BLevU" "\BLev^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bLevU" "\bLev^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BLev" "B" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bLev" "b" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bMin" "\underline{\bRat}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bRatE" "b}^{e" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BRatE" "B}^{e" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bRatU" "b}^{u" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BRat" "B" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bRat" "b" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bTargE" "\check{b}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BTargTarg" "\Target{\Target{\BRat}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bTargTarg" "\Target{\Target{\bRat}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BTarg" "\check{B}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bTarg" "\check{b}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\BU" "{B}^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\bU" "{b}^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cAgg" "\pmb{C}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CARA" "\alpha" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ccRat" "\mathsf{c}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CDF" "\mathcal{F}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CEndFunc" "\mathfrak{C}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cEndFunc" "\mathfrak{c}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cEss" "{c}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CE" "\CRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cE" "\cRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cFuncAbove" "\bar{\mathrm{c}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cFuncBelow" "\uline{\mathrm{c}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cFuncMax" "\bar{\bar{\mathrm{c}}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CFunc" "\mathrm{C}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cFunc" "\mathrm{c}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cFunc" "\mathrm{c}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CGroOverG" "\Upsilon" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CGroOverR" "\Phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CGroPF" "\Lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cGroPF" "\lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CGroPS" "\chi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\chiFunc" "\pmb{\chi}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Chi" "\mathrm{X}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CLevBF" "\mathbf{C}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cLevBF" "\mathbf{c}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CLevE" "\CLev^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cLevE" "\cLev^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cLevFunc" "\pmb{\cFunc}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CLevU" "\CLev^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cLevU" "\cLev^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cLev" "c" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CLev" "C" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Cons" "C" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cons" "c" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\corr" "\varrho" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cPDVFunc" "\mathbb{C}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CPDV" "\text{PDV($C$)}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cPPP" "\cons^{\prime\prime\prime}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cPP" "\cons^{\prime\prime}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cP" "\cons^{\prime}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cRatBF" "\pmb{c}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CRatE" "\CRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cRatE" "\cRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CRatU" "\CRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cRatU" "\cRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CRat" "C" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cRat" "c" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CRRA" "\rho" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CTargE" "\CTarg^{\null}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cTargE" "\Target{c}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cTargTarg" "\Target{\Target{\cRat}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CTarg" "\Target{C}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cTarg" "\Target{c}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\curr" "1" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Curr" "t" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\CU" "\CRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\cU" "\cRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\dRat" "d" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\debtLim" "\mathsf{d}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Debt" "D" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\debt" "d" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DeprFac" "\daleth" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Depr" "\daleth" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\depr" "\delta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\deprRte" "\delta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DiscAltuAdj" "\underline{\underline{\beth}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DiscAlt" "\beth" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Discount" "\beta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DiscRate" "\vartheta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DiscRte" "\vartheta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DiscFac" "\beta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DivGro" "\mathsf{G}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\divGro" "\mathsf{g}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Div" "D" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\div" "d" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\DLev" "D" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Dvdnd" "\mathbf{D}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\dvdnd" "d" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\edvdnd" "\grave{\dvdnd}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\EEndMap" "\mathsf{E}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\effUnits" "X" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\eFunc" "\mathrm{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ELev" "E" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ek" "\lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\EmpGro" "\Xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\empGro" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\empState" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\EpremLog" "\varphi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\EPrem" "\Phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\eprem" "\phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\EpShkInv" "\Ex[\pShk^{-1}]" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\erate" "\cancel{\mho}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\error" "\epsilon" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Err" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\err" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\err" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Estdr" "\sigma_{\risky}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Evarr" "\sigma_{\risky}^{2}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\EVarr" "\sigma_{\Risky}^{2}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\expend" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Ex" "\mathbb{E}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\FDist" "\mathcal{F}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\fDist" "\mathcal{f}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\FFunc" "\mathrm{F}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\fFunc" "\mathrm{f}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\FLev" "F" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\fLev" "f" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\fPP" "\mathrm{f}^{\prime\prime}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\FPP" "\mathrm{F}^{\prime\prime}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\fP" "\mathrm{f}^{\prime}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\FP" "\mathrm{F}^{\prime}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\GLev" "G" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\GovNW" "N" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\govNW" "n" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\GovSpend" "X" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\govSpend" "x" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Habit" "H" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Habit" "H" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\habit" "h" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Ham" "\mathcal{H}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\HARKcore" "\texttt{HARKcore}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hEndMin" "\underline{\mathfrak{h}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hEnd" "\mathfrak{h}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hFunc" "\mathrm{h}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Hi" "\hat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\HLev" "H" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\HLevBF" "\mathbf{H}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hLevBF" "\mathbf{h}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\HLev" "\pmb{H}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hLev" "\pmb{h}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hMin" "\underline{\h}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\HMin" "\underline{H}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hours" "\mathfrak{h}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Hours" "\mathfrak{H}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\HRat" "H" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\hRat" "h" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\h" "h" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\H" "H" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\iFunc" "\mathrm{i}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\IFunc" "\mathrm{I}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ILev" "I" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\iLev" "i" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\impg" "{\imath}_{\pGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ImpG" "{\Im}_{\PGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\impr" "{\imath}_{\rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ImpR" "{\Im}_{\Rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Inc" "{Y}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\inc" "{y}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\InvEpShkInv" "\acute{\psi}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\InvEpShkInv" "\underline{\psi}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Inv" "{I}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\inv" "{i}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\IRat" "I" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\iRat" "i" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\itc" "\zeta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\jFunc" "\mathrm{j}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\JLev" "J" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kapRent" "\varkappa" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kapShare" "\alpha" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Kap" "{K}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kap" "{k}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\KFunc" "\mathrm{K}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kFunc" "\mathrm{k}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\KLevBF" "\mathbf{K}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kLevBF" "\mathbf{k}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\KLev" "K" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kLev" "k" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kPriceAfterITC" "\mathscr{P}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kPrice" "\mathsf{P}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\KRat" "K" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kRat" "k" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kTargE" "\Target{k}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\kTarg" "\Target{k}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\labor" "\ell" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Labor" "L" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\labShare" "\nu" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Leisure" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\leisure" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\leiShare" "\zeta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\LGro" "\Lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\lGro" "\lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\LLevBF" "\mathbf{L}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\lLevBF" "\pmb{\ell}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\lLev" "\ell" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\LLev" "L" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Lo" "\check" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\LRat" "L" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MaxMaxMPC" "\bar{\bar{\kappa}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MaxMinMPC" "\hat{\underline{\kappa}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MaxMPC" "\bar{\kappa}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MaxMPS" "\PatR" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Mean" "\mathbb{M}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mEss" "\check{m}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ME" "\MRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mE" "\mRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mFunc" "\mathrm{m}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MinMinMPC" "\underline{\kappa}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MinMPC" "\uline{\kappa}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MinMPS" "\pZero^{1/\CRRA} \PatR" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MLevBF" "\mathbf{M}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mLevBF" "\mathbf{m}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mLevBF" "\mathbf{m}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mLevE" "\mLev^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MLev" "M" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mLev" "m" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPCE" "\MPC^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPCFunc" "\pmb{\kappa}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPCPPF" "\Pi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPCP" "\pi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPCU" "\MPC^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPC" "\kappa" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPSFunc" "\pmb{lambda}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MPS" "\lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MRatE" "\MRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mRatE" "\mRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MRat" "M" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mRat" "m" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MSS" "\breve{M}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mSS" "\breve{m}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mTarg" "\check{m}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\MU" "{M}^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\mU" "{m}^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\next" "2" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Next" "t+1" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\nFunc" "\mathrm{n}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\NLev" "N" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\nLev" "n" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\NRat" "N" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\nRat" "n" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Num" "N" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\OLevBF" "O" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\oLevBF" "\mathbf{o}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\OLev" "O" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\oLev" "\pmb{o}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ORat" "O" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\oRat" "o" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Pareto" "\zeta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PatPGroAdj" "\text{\pmb{\Thorn}}_{\acute{\PGro}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\patpGroAdj" "\text{\thorn}_{\acute{\pGro}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\patpGrohat" "\hat{\text{\thorn}}_{\pGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PatPGro" "\text{\pmb{\Thorn}}_{\PGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\patpGro" "\text{\thorn}_{\pGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PatR" "\text{\pmb{\Thorn}}_{\Rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\patr" "\text{\thorn}_{\rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PatU" "\text{\pmb{\Thorn}}_{\urate}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\patu" "\text{\thorn}_{\urate}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PatWGro" "\text{\pmb{\Thorn}}_{\WGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\patwGro" "\text{\thorn}_{\wGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Pat" "\text{\pmb{\Thorn}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pat" "\text{\thorn}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pDeadRate" "\grave{\cancel{\mathsf{d}}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pDead" "\mathfrak{D}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pDieRate" "\grave{\mathsf{d}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pDies" "\mathrm{d}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PDies" "\mathsf{D}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PDV" "\mathbb{P}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PGroAdj" "\underline{\PGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pGroAdj" "\underline{\pGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PGrouAdj" "\underline{\underline{\PGro}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pGrouAdj" "\underline{\underline{{\pGro}}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PGro" "\Gamma" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pGro" "\gamma" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\phiFunc" "\digamma" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PIHMPC" "\varkappa" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PInc" "P" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PLabor" "P" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Plabor" "P" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PLevBF" "\mathbf{P}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pLevBF" "\mathbf{p}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PLev" "P" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pLev" "\pmb{p}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PLev" "P" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PLives" "\cancel{\PDies}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pLives" "\cancel{\pDies}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pNotZero" "\cancel{\wp}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PopE" "\mathcal{E}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\popE" "e" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PopGro" "\Xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\popGro" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PopLev" "\pmb{N}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PopU" "\mathcal{U}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Pop" "L" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PostITC" "\cancel{\zeta}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\power" "\eta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pPDVFunc" "\mathbb{P}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PPDV" "\text{PDV($P$)}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pRat" "p" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Price" "\mathsf{P}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ProdFunc" "\mathrm{F}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ProdFunc" "\mathrm{F}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\prodFunc" "\mathrm{f}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\prudEx" "\omega" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\prud" "\eta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pSav" "\phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pShkMin" "\underline{\psi}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PShk" "\Psi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PermShkAgg" "\Psi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PermShk" "\Psi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\permShk" "\psi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pShk" "\psi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\permShkInd" "\psi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pshk" "\psi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PtyGro" "\Phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ptyGro" "\phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PtyLab" "\mathrm{Z}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ptyLab" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\PtyLev" "A" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ptyLev" "a" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\pZero" "\wp" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\QLev" "Q" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\q" "\koppa" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RCpnd" "\mathbf{R}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RevFunc" "\pmb{\Pi}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\revFunc" "\pmb{\pi}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Rev" "\Pi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rev" "\pi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rfree" "\mathsf{r}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Rfree" "\mathsf{R}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RFunc" "\mathrm{R}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RGross" "\breve{\mathsf{R}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rGross" "\breve{\mathsf{r}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RiskyAlt" "\acute{\mathbf{R}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\riskyAlt" "\acute{\mathbf{r}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\riskyshare" "\varsigma" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Risky" "\mathbf{R}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\risky" "\mathbf{r}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RLev" "R" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RnormWGro" "\mathcal{R}_{\WGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rnormwGro" "\mathit{r}_{\wGro}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Rnorm" "\mathcal{R}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rnorm" "\mathit{r}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Rport" "\pmb{\mathfrak{R}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rport" "\pmb{\mathfrak{r}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rProd" "\mathit{r}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Rprod" "\mathscr{R}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rprod" "\mathscr{r}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RProd" "\mathsf{R}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RSave" "\ushort{\Rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rsave" "\ushort{\rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\RBoro" "\bar{\Rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\rboro" "\bar{\rfree}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\R" "\Rfree" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\saveRate" "\grave{s}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Save" "S" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\save" "s" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SDF" "\MLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sdr" "\mRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Seniority" "\mathsf{X}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\seniority" "\mathsf{x}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SeverancePayment" "\mathcal{S}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SeveranceRatio" "\varsigma" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Severance" "\varsigma" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SE" "\SRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sE" "\sRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sFunc" "\mathrm{s}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\shk" "\phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Shk" "\Phi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkLogZeroLogStd" "\sigma_{\cancel{\ShkMeanOneLog}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkLogZeroLogVar" "\sigma_{\cancel{\ShkMeanOneLog}}^{2}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkLogZeroLog" "\cancel{\ShkMeanOneLog}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkLogZero" "\cancel{\ShkMeanOne}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkMeanOneLogStd" "\sigma_{\ShkMeanOneLog}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkMeanOneLogVar" "\sigma^{2}_{\ShkMeanOneLog}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkMeanOneLog" "\theta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ShkMeanOne" "\Theta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SLevBF" "\mathbf{S}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sLevBF" "\mathbf{s}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SLevE" "\SLev^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sLevE" "\sLev^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SLevU" "\SLev^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sLevU" "\sLev^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SLev" "S" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sLev" "s" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\srate" "\varsigma" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SRatE" "\SRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sRatE" "\sRat^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SRatU" "\SRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sRatU" "\sRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SRat" "S" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sRat" "s" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\STargE" "\Target{\SRat}^{\null}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sTargE" "\Target{\sRat}^{\null}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\STargTarg" "\Target{\Target{\SRat}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sTargTarg" "\Target{\Target{\sRat}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\STarg" "\Target{\SRat}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sTarg" "\Target{\sRat}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Steady" "\bar" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Stocks" "{S}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\stocks" "{s}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\straight" "\Pi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Surplus" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\surplus" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\SU" "\SRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\sU" "\sRat^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Target" "\check" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxCombInv" "\mathcal{T}^{-1}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxComb" "\mathcal{T}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxCorp" "\tau" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\taxDep" "\partial" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxFree" "\cancel{\Tax}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxLev" "T" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxNetTrans" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\taxNetTrans" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxPaid" "T" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxRate" "t" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TaxUI" "\tau" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Tax" "\tau" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tax" "\tau" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tBak" "\pmb{n}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TEatBak" "\mathtt{q}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TEat" "\TEnd" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TEndBak" "\mathsf{p}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TEnd" "T" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TermTime" "T" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tFwd" "n" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tHorOfm" "\pmb{n}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tHor" "\mathsf{n}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\timeRate" "\vartheta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tinyAmount" "\epsilon" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TLev" "T" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TMap" "\mathscr{T}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tNow" "t" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tShkAll" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tShkEmpMin" "\underline{\theta}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TShkEmp" "\Theta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tShkEmp" "\theta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tShkEmp" "\theta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tranShkInd" "\theta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TranShkAgg" "\Theta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\TShk" "\Xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tShk" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tshk" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tSS" "t" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\tThen" "\tau" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uFunc" "{\mathrm{u}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uInvEpShkuInv" "\underline{\underline{\psi}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ULev" "U" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uLev" "u" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\unins" "\zeta" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uPDVFunc" "\mathbb{U}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uPmt" "\mu" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uPPP" "{\mathrm{u}^{\prime\prime\prime}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uPP" "{\mathrm{u}^{\prime\prime}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\uP" "{\mathrm{u}^{\prime}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\urate" "\mho" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\utilFunc" "\mathrm{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\util" "u" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ValAlt" "\mathcal{V}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\valfn" "\mathrm{v}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Value" "\mathrm{V}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VEndFunc" "\mathfrak{V}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vEndFunc" "\mathfrak{v}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VEnd" "\mathfrak{V}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vEnd" "\mathfrak{v}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vEss" "\check{v}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VE" "{V}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vE" "{v}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vFirm" "\mathrm{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VFunc" "\mathrm{V}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vFunc" "\mathrm{v}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VInv" "\Lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vInv" "\scriptstyle \Lambda \displaystyle" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vk" "\lambda" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vLevBF" "\mathbf{v}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VLevFunc" "\pmb{\mathrm{V}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vLevFunc" "\pmb{\mathrm{v}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VLev" "V" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vLev" "v" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vNorm" "\mathrm{w}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VNum" "V" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vNum" "v" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vOptAlt" "\Alt{\tilde{\mathfrak{v}}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vOpt" "\tilde{\mathfrak{v}}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VRat" "V" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vRat" "v" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vTarg" "\Target{\vRat}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\VU" "{V}^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\vU" "{v}^{u}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Wage" "\mathsf{W}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wage" "\mathsf{w}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WAllLev" "\mathbf{O}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wAllLev" "\mathbf{o}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WAllRat" "O" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wAllRat" "o" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WAll" "{O}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wAll" "{o}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WBeg" "\KLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wBeg" "\kLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Wealth" "O" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wealth" "o" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WEndRat" "\ARat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wEndRat" "\aRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WEnd" "\ALev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wEnd" "\aLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Wend" "\ARat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wend" "\aRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wFunc" "\mathrm{w}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WGroPF" "\mathsf{G}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WGro" "\mathsf{G}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wGro" "\mathsf{g}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\whumMin" "\underline{\hRat}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WHum" "\HLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wHum" "\hLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Whum" "\HRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\whum" "\hRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WLev" "W" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wLev" "\pmb{w}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WMid" "\BLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WMid" "\BLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wMid" "\bLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Wmid" "\BRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wmid" "\bRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WMkt" "\MLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wMkt" "\mLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wmkt" "\mLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wNet" "x" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WNet" "X" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WPre" "{K}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wPre" "{k}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wRat" "o" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WRat" "O" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wTot" "\mathbf{o}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\WTot" "\mathbf{O}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\wtot" "o" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Wtot" "O" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\xFer" "\chi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\XFer" "X" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\xFunc" "\mathrm{x}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\XLev" "X" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\xLev" "x" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\xpend" "\xi" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\XperGro" "\mathsf{X}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\xperGro" "\mathsf{x}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\XRat" "X" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\xRat" "x" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\yFunc" "\mathrm{y}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\yLevBF" "\mathbf{y}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\YLev" "Y" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\yLev" "y" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\YRat" "Y" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\yRat" "y" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\yTargE" "\check{y}^{e}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\yTarg" "\check{y}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\zAgg" "\pmb{Z}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\zFunc" "\mathrm{z}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ZLevBF" "\mathbf{Z}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\zLevBF" "\mathbf{z}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\zLevBF" "\pmb{z}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ZLev" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\zLev" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\ZRat" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\zRat" "z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\NFALev" "\NLev" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\NFARat" "\NRat" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\NI" "Z" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\GDPLev" "\pmb{P}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\GDPRat" "P" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\GDPGro" "\gimel" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\gdpLev" "\pmb{p}" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\gdpRat" "p" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\weight" "\omega" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
rpl "\Severance" "\kappa" /Volumes/Data/Work/BufferStock/BufferStockTheory/Latest/Equations/veqn.tex-Plain.tex
